BlogPage/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
        path('', views.post_list, name='post_list'),
        # path('', views.PostListView.as_view(), name='post_list'),
        path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
        path('<slug:slug>/', views.post_detail, name='post_detail'),
        path('<int:post_id>/share/', views.post_share, name='post_share'), # TODO: change id to slug
        path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
        ]

BlogPage/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
        path('admin/', admin.site.urls),
        path('blog/', include('blog.urls', namespace='blog')),
        path(
            'sitemap.xml',
            sitemap,
            {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'
            )
        ]

BlogPage/blog/models.py
from taggit.managers import TaggableManager

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return (
                super().get_queryset().filter(status=Post.Status.PUBLISHED)
                )

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete = models.CASCADE,
            related_name = 'blog_posts'
            )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
            max_length=2,
            choices=Status,
            default=Status.DRAFT
            )
    
    tags = TaggableManager()
    objects = models.Manager() # default manager
    published = PublishedManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
                models.Index(fields=['-publish']),
                ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

            original_slug = self.slug
            counter = 1
            while Post.objects.filter(slug=self.slug).exists():
                self.slug = f'{original_slug}-{counter}'
                counter += 1

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
                'blog:post_detail',
                args=[self.slug]
                )

class Comment(models.Model):
    post = models.ForeignKey(
            Post,
            on_delete=models.CASCADE,
            related_name='comments'
            )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
                models.Index(fields=['created']),
                ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

BlogPage/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

BlogPage/blog/views.py
from django.shortcuts import render, get_object_or_404

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.views.decorators.http import require_POST

from taggit.models import Tag

from .forms import EmailPostForm, CommentForm
from .models import Post, Comment


# Create your views here.

class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag]) # find posts with the tag or including the tag

    # Pagination with 2 posts per page
    paginator = Paginator(post_list, 2)

    # if there is not a page parameter, display the page 1
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # if the page number is out of range
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # if the page number is not an integer
        posts = paginator.page(1)

    return render(
            request,
            'blog/post/list.html',
            {'posts': posts,
             'tag': tag}
            )

def post_detail(request, slug):
    try:
        post = Post.published.get(slug=slug)
    except Post.DoesNotExist:
        raise Http404("No post found")

    comments = post.comments.filter(active=True)
    form = CommentForm()

    # Similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    context = {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts,
            }
    return render(
            request,
            'blog/post/detail.html',
            context
            )


def post_detail_alt(request, slug):
    post = get_object_or_404( Post, id=id,
            status=Post.Status.PUBLISHED,
            slug=slug)
    return render(request,
                  'blog/post/detail.html',
                  {'post': post}
                  )

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data # cleaned data
            post_url = request.build_absolute_uri(
                    post.get_absolute_url()
                    )
            subject = f"{cd['name']} ({cd['email']}) recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"

            send_mail(
                    subject = subject,
                    message = message,
                    from_email = None,
                    recipient_list = [cd['to']]
                    )
            sent = True
    else:
        form = EmailPostForm()
    context = {
           'post': post,
           'form': form,
           'sent': sent
           }
    return render(request, 'blog/post/share.html', context)

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # create a Comment object but don't save it to the database yet
        comment = form.save(commit=False)
        comment.post = post
        # save the comment to the database
        comment.save()
    context = {
            'post': post,
            'form': form,
            'comment': comment
            }
    return render(request, 'blog/post/comment.html', context)

BlogPage/blog/templates/blog/layout.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
	<div id="content">
	{% block content %}
	{% endblock %}
	</div>
	<div id="sidebar">
    	<h2>My blog</h2>
    	<p>This is my blog. I have written {% total_posts %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 5 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts 3 as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

BlogPage/blog/templates/blog/post/comment.html
{% extends "blog/layout.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

BlogPage/blog/templates/blog/post/detail.html
{% extends "blog/layout.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    {% include "blog/post/includes/similar_posts.html" with similar_posts=similar_posts %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

BlogPage/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    <div class="left">
        {{ form.name.as_field_group }}
    </div>
    <div class="left">
        {{ form.email.as_field_group }}
    </div>
    {{ form.body.as_field_group }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

    
    

BlogPage/blog/templates/blog/post/includes/similar_posts.html
<h2>Similar posts</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
{% empty %}
    There are no similar posts yet.
{% endfor %}

BlogPage/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %} 
        <li>                                                                                                                                   
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> 
        </li> 
    {% empty %}
        <li>No posts yet.</li>
    {% endfor %} 
</ul> 

BlogPage/blog/templates/blog/post/list.html
{% extends "blog/layout.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
	        <a href="{{ post.get_absolute_url }}">
             {{ post.title }}
            </a>
        </h2>
        <p class'tags'>Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

BlogPage/blog/templates/blog/post/share.html
{% extends 'blog/layout.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}  
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Send</button>
        </form>
    {% endif %}
{% endblock %}

BlogPage/blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>